# Generated by Django 6.0.4 on 2026-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='booking',
        ),
        migrations.AlterField(
            model_name='payments',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='type_fly',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterModelTable(
            name='payments',
            table='payments',
        ),
    ]
