# Generated by Django 6.0.4 on 2026-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='aircraft',
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='bookings_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='from_city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='flight',
            name='number_of_race',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='to_city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterModelTable(
            name='flight',
            table='flights',
        ),
    ]
