# Generated by Django 6.0.4 on 2026-04-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='model',
            new_name='models',
        ),
        migrations.AlterModelTable(
            name='aircraft',
            table='aircraft',
        ),
    ]
