# Generated by Django 6.0.4 on 2026-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='flight',
        ),
        migrations.AddField(
            model_name='bookings',
            name='flights_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='payments_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='passport',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='bookings',
            table='bookings',
        ),
    ]
